# Global options
baseURL = "https://spindro.github.io/"
canonifyURLs = true
copyright = "© 2024 by Indro Spinelli. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "INDRO SPINELLI"
googleAnalytics = "UA-125836689-1"

# Main menu
[[menu.main]]
    name = "ABOUT"
    url  = "/about"
    weight = 2

[[menu.main]]
    name = "ACTIVITIES"
    url  = "/activities"
    weight = 2
[[menu.main]]
    name = "TEACHING"
    url  = "/teaching"
    weight = 2

[[menu.main]]
    name = "PUBLICATIONS"
    url  = "/publications"
    weight = 2


[params]
    [params.head]
        author = "Indro Spinelli"
        custom_css = "/custom.css"
        description = "spindro"
        keywords = ["trusthworthy machine learning", "academic", "graph neural networks"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Oswald"
        body_font = "Raleway"

    [params.colors]
        theme_color = "#192928"
        background_color = "#FFFFFF"
        text_color = "#192928"
        link_color = "#BFEB89"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:indro.spinelli@uniroma1.it"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/spindro"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = "https://scholar.google.com/citations?user=0glmB_UAAAAJ&hl=en"
            weight = 3
        [params.social.twitter]
            name = "Twitter"
            class = "fab fa-twitter"
            url = "https://twitter.com/IndroSpinelli"
            weight = 5
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/indro-spinelli-770380123/"
            weight = 6


# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
