# Global options
baseURL = "https://spindro.github.io/"
canonifyURLs = true
copyright = "© 2023 by Indro Spinelli. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Indro Spinelli"
googleAnalytics = "UA-125836689-1"
# Main menu
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 2
#[[menu.main]]
#    name = "Teaching"
#    url  = "/teaching"
#    weight = 2
# Customization options

[params]
    [params.head]
        author = "Indro Spinelli"
        custom_css = "/custom.css"
        description = "spindro"
        keywords = ["trusthworthy machine learning", "academic", "graph neural networks"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Roboto Slab"
        body_font = "Roboto Slab"

    [params.colors]
        theme_color = "#fec308"
        background_color = "#FAF5E9"
        text_color = "#123308"
        link_color = "#fec308"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:indro.spinelli@uniroma1.it"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/spindro"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = "https://scholar.google.com/citations?user=0glmB_UAAAAJ&hl=en"
            weight = 3
        [params.social.twitter]
            name = "Twitter"
            class = "fab fa-twitter"
            url = "https://twitter.com/IndroSpinelli"
            weight = 5
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/indro-spinelli-770380123/"
            weight = 6
        [params.social.orcid]
            name = "ORCID iD"
            class = "fab fa-orcid"
            url = "https://orcid.org/0000-0003-1963-3548"
            weight = 7

# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
